# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [3]:
import numpy as np

array = np.random.randint(1,20,size=(5,5))
print(array)

array[:,2] = 1
print(array)

[[13 10 14 15 14]
 [15 11  8 12  5]
 [ 3  1 19 16 17]
 [ 3 15  7 16 17]
 [ 3 17  8 12 12]]
[[13 10  1 15 14]
 [15 11  1 12  5]
 [ 3  1  1 16 17]
 [ 3 15  1 16 17]
 [ 3 17  1 12 12]]


In [8]:
a = np.arange(1,17).reshape(4,4)
print(a)


np.fill_diagonal(a,0)
print(a)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [11]:
b = np.arange(1,37).reshape(6,6)
print(b)

sub = b[2:5,1:4]
print(sub)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [12]:
# Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[ 6 20  1 10 12]
 [17  3  1 20 20]
 [20 17 11 18  9]
 [20 16 17 19 11]
 [ 3  1 11  6 18]]
Border elements:
[ 6 20  1 10 12  3  1 11  6 18 17 20 20 20  9 11]


In [13]:
# Create two NumPy arrays of shape (3, 4) filled with random integers
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)


Array 1:
[[ 7  7  4  7]
 [ 6  4  3  3]
 [10 10  7  1]]
Array 2:
[[ 2  1  1  9]
 [ 4  8 10  9]
 [ 4  5  3  6]]
Element-wise addition:
[[ 9  8  5 16]
 [10 12 13 12]
 [14 15 10  7]]
Element-wise subtraction:
[[ 5  6  3 -2]
 [ 2 -4 -7 -6]
 [ 6  5  4 -5]]
Element-wise multiplication:
[[14  7  4 63]
 [24 32 30 27]
 [40 50 21  6]]
Element-wise division:
[[3.5        7.         4.         0.77777778]
 [1.5        0.5        0.3        0.33333333]
 [2.5        2.         2.33333333 0.16666667]]


In [14]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


In [22]:
array = np.random.randint(1,101,size=(5,5))
print(array)
print(f"Mean :{np.mean(array)}")
print(f"Median :{np.median(array)}")
print(f'Standard deviation :{np.std(array)}')
print(f"Variance :{np.var(array)}")

[[16 63 21 27 64]
 [70  4 18 82 32]
 [83 42 47  5 42]
 [29  4 66  5 48]
 [61 71 58 57 51]]
Mean :42.64
Median :47.0
Standard deviation :24.652594183979907
Variance :607.7504


In [25]:
array = np.arange(1,10).reshape(3,3)
print(array)

normalize = (array - np.mean(array))/np.std(array)
print(normalize)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [26]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

Original array:
[[10  3  4]
 [ 8  3 10]
 [ 5 10  8]]
1D array:
[9 7 1]
Resulting array:
[[19 10  5]
 [17 10 11]
 [14 17  9]]


In [27]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[ 3  4  2  1]
 [ 6 10  9  4]
 [ 3  7 10  8]
 [ 5  4  8  1]]
1D array:
[4 8 8 6]
Resulting array:
[[-1  0 -2 -3]
 [-2  2  1 -4]
 [-5 -1  2  0]
 [-1 -2  2 -5]]


In [31]:
arr = np.random.randint(1,20,size=(3,3))
print(arr)

[[ 5  2  1]
 [12  7 10]
 [ 2 14  2]]


In [32]:
np.linalg.inv(arr)

array([[ 0.26033058, -0.02066116, -0.0268595 ],
       [ 0.00826446, -0.01652893,  0.0785124 ],
       [-0.31818182,  0.13636364, -0.02272727]])

In [33]:
np.linalg.det(arr)

np.float64(-484.0000000000002)

In [34]:
np.linalg.eigvals(arr)

array([18.38762247,  3.38605097, -7.77367344])

In [39]:
arr1 = np.random.randint(1,100,size=(2,3))
arr2 = np.random.randint(1,100,size=(3,2))

arrM = np.dot(arr1,arr2)
#print(f'Matrix Multipliction of \n{arr1} and \n{arr2} is \n{arrM}')
print(arrM)

[[ 3989  2686]
 [17985  9837]]


In [46]:
arra = np.arange(1,10).reshape((3,3))
print(arra)
print(arra.reshape((9,1)))
print(arra.reshape((1,9)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[1 2 3 4 5 6 7 8 9]]


In [49]:
ara = np.random.randint(1,10,size=(3,3))
print(ara)
ara1 = ara.flatten()
print(ara1)
print(ara1.reshape((3,3)))

[[1 4 5]
 [2 5 2]
 [6 7 1]]
[1 4 5 2 5 2 6 7 1]
[[1 4 5]
 [2 5 2]
 [6 7 1]]


In [50]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[ 5  1  2  2 15]
 [12  9  2 19 20]
 [13  4  6 13 17]
 [ 5  8 20 19 12]
 [10 10 13 14  6]]
Corner elements:
[ 5 15 10  6]


In [51]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[ 9 17  3  7]
 [ 8 20 16  7]
 [19 12 10 12]
 [10 16  4  9]]
Modified array:
[[ 9 10  3  7]
 [ 8 10 10  7]
 [10 10 10 10]
 [10 10  4  9]]


In [ ]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [2]:
import numpy as np
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [3]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 3  1 12  1]
 [ 8  4  3  9]
 [11 15 19  4]
 [ 4 12 19 15]]
Masked array:
[[3 1 -- 1]
 [8 4 3 9]
 [-- -- -- 4]
 [4 -- -- --]]
Sum of unmasked elements: 37


In [4]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")

print(masked_array)

Original array:
[[ 3  7 15]
 [ 8 15 20]
 [ 6  7 18]]
Masked array:
[[-- 7 15]
 [8 -- 20]
 [6 7 --]]
Modified masked array:
[[10  7 15]
 [ 8 10 20]
 [ 6  7 10]]
